branches:
  only:
  - master
language: ruby
rvm:
- 1.9.3
before_script:
- git config --global user.name "Teracy Bot"
- git config --global user.email "teracy.com@gmail.com"
- export REPO_URL="https://$GH_TOKEN@github.com/$GH_REPO.git"
- rake setup_github_pages[$REPO_URL]
- git checkout -- _config.yml
script: bundle exec rake generate
after_script:
- bundle exec rake deploy
env:
  global:
  - GH_REPO="teracy-official/spec"
  - secure: UZOZTyYbKVL4q2MZct7EJ/9KHr7wn1zKM9SFhb+McwfYaP8rZQLvzaMCdoDi+UjCHvwQ7QySdcmfb8LNen2ugB3RXfB7x6VQsdljIxX7rvszpf1HSJfay5Ms1RHwNXDLcx41ubOELWcWCSIdGgTLul8jAq8H+yU4ldGw9LU1yHA=
